server:
  servlet:
    context-path: /log
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm_log?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      maxActive: 300
      initialSize: 50
      minIdle: 50
      testOnBorrow: false
      testWhileIdle: true
      validation-query: select 1
  transaction:
    default-timeout: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: log
      enable-auto-commit: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      springframework:
        web: INFO