server:
  servlet:
    context-path: /api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      maxActive: 300
      initialSize: 50
      minIdle: 50
      testOnBorrow: false
      testWhileIdle: true
      validation-query: select 1
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
        max-wait: 10000
  mail:
    host: smtp.126.com
    username: buerchao@126.com
    password: WNWJOZCZNVATCFTP
    port: 25
    protocol: smtp
    default-encoding: utf-8
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
#    servlet:
#      content-type: text/html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
#  mapper-locations: classpath*:com/buerc/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

#日志级别
logging:
  level:
    org:
      springframework:
        web: TRACE
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.resources.add-mappings=false

#jwt token配置
jwt:
  secret: buerc-elm
  expiration: 7200
  tokenHead: Bearer
  refreshTime: 30
rsa:
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCRkNokhMqpFS6QOzGIgXeI4/QXw7dGnUNHuvNinl2d2r80LmYSTYUq7qGYSmKaFMBNd/wbSVvxPLEqdxFUukIKuCtFQxO4ZhYq6+eyHCbJgZn8/uxMg6tb5xGUmV4dQX1mf7dLV1jF3+1Wi/DB/csW5TcMVeCpFeJktLNb+S/tMwIDAQAB
  privateKey: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAJGQ2iSEyqkVLpA7MYiBd4jj9BfDt0adQ0e682KeXZ3avzQuZhJNhSruoZhKYpoUwE13/BtJW/E8sSp3EVS6Qgq4K0VDE7hmFirr57IcJsmBmfz+7EyDq1vnEZSZXh1BfWZ/t0tXWMXf7VaL8MH9yxblNwxV4KkV4mS0s1v5L+0zAgMBAAECgYAjcLTrtzjwOawAiajhp0PHHFjNgGUa2CcNS8L9+7inOh7bQYCwbBdEAJ1vSoz/HpZDRjcnHZE5BqHLyPl7O23gdsl96OLROXMVw0ZJXqTJsX215eFnnGJqvWiAMllh6xHsHcbjffsl1Xhupu7XZAqDgaWNOBbnjVENedWqgqf9QQJBAOYp0XB/ysieaLrIgUpMdrSWvL5aYahgzxfA2HMNTmCQ5hivT5gytus1Bk+mA4oHPKWbC5nXNXKDfZJkMHdKP6kCQQCh5/aTew7ar+z1sZEiOzl6jjPv2N9njGi+1Y32B5QV76jGOItsgtxPjrmfnPsd7jddsPFOSwu7nqZE+nOSiv97AkAQJeLx16VsieCjKioYAmFZrjGz0TeEzrX43qjQ+aAEGmZqWPJmpTg8LE4zDFy3NGbG36fitTykuiD3Qlw8IlNxAkBOBZifzaeE306Tv/QuyNeUJb8FkD9oiRNZE1SMAW7te0ab71fQ/ObqN99f+ahR7iAkOEaw8h0/Vt7NUtwq/GzNAkBW+SmlEtAelASJzMn6L+Y4Vi9gMW5EOJNrlGOaZ1eeOVYPCLMKUvvtHehloIKkhPoB68DAAUvTKP5wHILnfW+a
app:
  url:
    permission: http://127.0.0.1:${server.port}${server.servlet.context-path}