server:
  servlet:
    context-path: /api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      maxActive: 300
      initialSize: 50
      minIdle: 50
      testOnBorrow: false
      testWhileIdle: true
      validation-query: select 1
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-idle: 8
        max-wait: 10000
  mail:
    host: smtp.126.com
    username: buerchao@126.com
    password: WNWJOZCZNVATCFTP
    port: 25
    protocol: smtp
    default-encoding: utf-8
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
#    servlet:
#      content-type: text/html

#日志级别
logging:
  level:
    org:
      springframework:
        web: TRACE
#spring.mvc.throw-exception-if-no-handler-found=true
#spring.resources.add-mappings=false

#jwt token配置
jwt:
  secret: buerc-elm
  expiration: 7200
  tokenHead: Bearer
  refreshTime: 30
